name: connectivity_test
description: Test project to check Networking in flutter.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  # Handling Network
  http: ^0.12.1
  # Connectivity Checking
  connectivity: ^0.4.8+6
  # State Management
  provider: ^4.1.2
  # Dependency Injection
  get_it: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
